### ISSUE TITLE
some wrong with training D-NeRF datasets

### ISSUE THREAD

**Issue by Spphire** [sarafridov/K-Planes#12]
i downloaded a D-NeRF dataset to train as monocular video. using D-NeRF/dnerf_explicit.py as config.
But it said that i miss the file "poses_bounds.npy" in dataset. 
did i download a wrong D-NeRF dataset? What should i do?

more informations:

error:
![image](https://user-images.githubusercontent.com/56157591/225232196-10a6a818-df88-4944-904a-2e1a6d217499.png)

where i download the dataset:
https://github.com/albertpumarola/D-NeRF    
![image](https://user-images.githubusercontent.com/56157591/225232380-f4527208-f18b-4c2f-8b76-ba91f64ef4bb.png)

dataset construction:
![image](https://user-images.githubusercontent.com/56157591/225232663-1ff2d81d-24d3-47c9-90c8-b3097c2a0875.png)
information of the poses of camera is in .json files i thought

**Comment by Giodiro** [comment]
Hi @Spphire 
The dataset is not being detected correctly. The logic for detecting if it's D-NeRF or another dataset, checks whether the data directory includes the string "dnerf". 
If you can change your directory structure, that's the easiest fix. Otherwise you can modify the detection logic [here](https://github.com/sarafridov/K-Planes/blob/c1a28713e2df769c80828a9f5bebc95f964259ee/plenoxels/datasets/video_datasets.py#L60).

Feel free to re-open the issue if this doesn't solve the error.
