### ISSUE TITLE
Temporal difference (IST) strategy

### ISSUE THREAD

**Issue by xuyaojian123** [sarafridov/K-Planes#40]
![image](https://github.com/sarafridov/K-Planes/assets/51220835/fc3a6390-16ca-4f8e-9b22-97004432b61d)

could you explain why temporal difference (IST) strategy cannot be used for monocular videos?

**Comment by sarafridov** [comment]
The temporal difference strategy works like this: Given a fixed-position camera, compare pixel values over time to detect motion, and then prioritize training with those pixels that change value. If the camera is moving between different timesteps, then you can't discover and prioritize motion by doing pixel-wise temporal differencing because all the pixels will exhibit camera motion.

**Comment by xuyaojian123** [comment]
Thanks your reply. You may understand me wrong, I understand how IST is calculated, I want to ask why IST does not apply to monocular videos (only one fixed camera)?

**Comment by sarafridov** [comment]
Ah, usually when people say "monocular videos" in the context of radiance field modeling, they mean a single camera that moves around over time. If there is only one camera and it doesn't move, then you don't get enough information for a volumetric reconstruction (at least, not without relying on very strong depth priors).

**Comment by xuyaojian123** [comment]
Than you very much! By the way, help me see see issue https://github.com/sarafridov/K-Planes/issues/38#issue-2002214935.
